name: tech_blog
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  http: ^0.13.4
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  flutter_gen: ^4.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # example:
  fonts:
    - family: dana
      fonts:
        - asset: assets\fonts\DANA-BOLD.TTF
          weight: 700

        - asset: assets\fonts\DANA-REGULAR.TTF
          weight: 300

